
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 1753;
const int acc_off_y = 40;
const int acc_off_z = -1851;
const float acc_scale_x = 15035.484211;
const float acc_scale_y = 17223.369842;
const float acc_scale_z = 17441.494431;

const int magn_off_x = -1;
const int magn_off_y = -96;
const int magn_off_z = 14;
const float magn_scale_x = 537.363763;
const float magn_scale_y = 527.111246;
const float magn_scale_z = 500.945788;
